// TMDB API 配置（token 由 server.js 通过 /env.js 注入，file:// 协议下为空）
const tmdb_token = (typeof window !== 'undefined' && window.TMDB_TOKEN) || '';
// 检测是否使用 file:// 协议，如果是则强制使用本地数据
const isFileProtocol = !tmdb_token || window.location.protocol === "file:";
const CONFIG = {
  USE_MOCK: isFileProtocol ? true : false, // true: 使用本地JSON(mock)，false: 使用真实API
  TMDB_TOKEN: tmdb_token,
  TMDB_BASE_URL: "https://api.themoviedb.org/3",
  IMAGE_BASE_URL: "https://image.tmdb.org/t/p",
  LOCAL_DATA_BASE: isFileProtocol ? "./data" : "/data", // 相对路径用于file://，绝对路径用于服务器
  LOCAL_SYNC_BASE: "/sync", // 同步写入接口前缀（由本地服务提供）
};

// 在 file:// 协议下，禁用 Service Worker 中的网络错误日志
if (isFileProtocol && "serviceWorker" in navigator) {
  navigator.serviceWorker
    .getRegistrations()
    .then((registrations) => {
      registrations.forEach((registration) => {
        registration.unregister().catch(() => {});
      });
    })
    .catch(() => {});

  // 阻止 Service Worker 的错误日志
  window.addEventListener(
    "error",
    (event) => {
      if (event.message && event.message.includes("[workbox]")) {
        event.preventDefault();
      }
    },
    true,
  );

  // 阻止 fetch 错误导出
  window.addEventListener("unhandledrejection", (event) => {
    if (
      event.reason &&
      (event.reason.toString().includes("[workbox]") ||
        event.reason.toString().includes("Failed to fetch"))
    ) {
      event.preventDefault();
    }
  });
}

// Mock数据（从真实API保存）
const MOCK_DATA = {
  upcoming: [
    {
      adult: false,
      backdrop_path: "/AecGG1XVCmkk7fT10ko3FC0dLIP.jpg",
      genre_ids: [28, 14, 53],
      id: 1043197,
      original_language: "en",
      original_title: "Dust Bunny",
      overview:
        "小女孩奥萝拉深信，家中的地板下潜伏着一只吃掉她全家的神秘怪物。 她决定向隔壁冷峻的邻居求助，因为她发现这位看似平凡的男人竟是一名职业杀手！",
      popularity: 367.8433,
      poster_path: "/iZl0DTHJIQQhLyh53CYQOX12l6O.jpg",
      release_date: "2025-12-11",
      title: "尘兔",
      video: false,
      vote_average: 6.826,
      vote_count: 88,

      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 1019,
            known_for_department: "Acting",
            name: "麦斯·米科尔森",
            original_name: "Mads Mikkelsen",
            popularity: 6.1451,
            profile_path: "/AsX4bdvZ8UCayWTmAf9lAqOA8V7.jpg",
            cast_id: 7,
            character: "Intriguing Neighbor",
            credit_id: "636430fc5ca704007ac1e3b8",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 3969369,
            known_for_department: "Acting",
            name: "Sophie Sloan",
            original_name: "Sophie Sloan",
            popularity: 3.0426,
            profile_path: "/orJhg6oQ4h2qdBSTaKSwdEvD4xa.jpg",
            cast_id: 14,
            character: "Aurora",
            credit_id: "676849eca0c300283c749d44",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 10205,
            known_for_department: "Acting",
            name: "西格妮·韦弗",
            original_name: "Sigourney Weaver",
            popularity: 4.2766,
            profile_path: "/wTSnfktNBLd6kwQxgvkqYw6vEon.jpg",
            cast_id: 10,
            character: "Laverne",
            credit_id: "64922b3e6c449c00fd27bbc8",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 83854,
            known_for_department: "Acting",
            name: "大卫·达斯马齐连",
            original_name: "David Dastmalchian",
            popularity: 2.3599,
            profile_path: "/nER1Vzhk51pGHb60KBF1Ja5tEXA.jpg",
            cast_id: 11,
            character: "Conspicuously Inconspicuous Man",
            credit_id: "656c2872cede69011fc3af7f",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 1851642,
            known_for_department: "Acting",
            name: "希拉·阿蒂姆",
            original_name: "Sheila Atim",
            popularity: 0.7246,
            profile_path: "/esAjvG2IXvzQODNEHVCVsc4WALI.jpg",
            cast_id: 13,
            character: "Brenda",
            credit_id: "662f58f2e33f83012b221137",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 1441919,
            known_for_department: "Acting",
            name: "Caspar Phillipson",
            original_name: "Caspar Phillipson",
            popularity: 0.4169,
            profile_path: "/2344bWYuEN4NTL4ZVXBCxvpucN0.jpg",
            cast_id: 120,
            character: "Father",
            credit_id: "693c044779fd978a5f360ae7",
            order: 5,
          },
          {
            adult: false,
            gender: 1,
            id: 3402,
            known_for_department: "Acting",
            name: "Line Kruse",
            original_name: "Line Kruse",
            popularity: 0.3759,
            profile_path: "/AqGjJgCMeXYBP18DR6XV0OI3Ydv.jpg",
            cast_id: 121,
            character: "Mother",
            credit_id: "693c045228a5b01f080c1849",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 30616,
            known_for_department: "Acting",
            name: "丽贝卡·亨德森",
            original_name: "Rebecca Henderson",
            popularity: 0.5791,
            profile_path: "/6e9M5qhNr0TaziQxWLS91SZiS0D.jpg",
            cast_id: 12,
            character: "Intimidating Woman",
            credit_id: "662f58eb03bf84012aeb4230",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/sK3z0Naed3H1Wuh7a21YRVMxYqt.jpg",
      genre_ids: [9648, 53],
      id: 1368166,
      original_language: "en",
      original_title: "The Housemaid",
      overview:
        "　　生活困顿的米莉，得到了一份在富豪夫妇妮娜和安德鲁家中做家政的工作。但这份看似理想的工作，很快便变得危机四伏。米莉发现，这个富足家庭光鲜亮丽的外表之下，隐藏着远比她想象中更为危险的秘密。她置身于一个充满阴谋与恐惧的环境中，而这个家庭的悲剧命运也随着交织着秘密、丑闻与权力游戏的风暴在逐渐展开。",
      popularity: 167.4664,
      poster_path: "/p7R6ddRrTdEwjZ7gXLFnyYuULrM.jpg",
      release_date: "2025-12-18",
      title: "家弑服务",
      video: false,
      vote_average: 7.09,
      vote_count: 491,
      credits: {
        cast: [
          {
            adult: false,
            gender: 1,
            id: 115440,
            known_for_department: "Acting",
            name: "西德妮·斯维尼",
            original_name: "Sydney Sweeney",
            popularity: 25.0914,
            profile_path: "/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg",
            cast_id: 1,
            character: "Millie Calloway",
            credit_id: "67055a48ccbb4e7f1669de8e",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 71070,
            known_for_department: "Acting",
            name: "阿曼达·塞弗里德",
            original_name: "Amanda Seyfried",
            popularity: 8.6432,
            profile_path: "/gtBUIpZ3dvLpOMIVORxE6sHSyZj.jpg",
            cast_id: 2,
            character: "Nina Winchester",
            credit_id: "67055a5b2ae7eb9084c0240a",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 1855143,
            known_for_department: "Acting",
            name: "布兰登·斯克莱纳",
            original_name: "Brandon Sklenar",
            popularity: 6.0294,
            profile_path: "/1f1NMi0IYL5p1BHVyV9IoYcwzJt.jpg",
            cast_id: 14,
            character: "Andrew Winchester",
            credit_id: "671ac4a16d6b705dc8713fe6",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 2349355,
            known_for_department: "Acting",
            name: "米凯莱·莫罗尼",
            original_name: "Michele Morrone",
            popularity: 4.0343,
            profile_path: "/saKjzGAuw8Fiutlv9LweLjAti0Z.jpg",
            cast_id: 15,
            character: "Enzo",
            credit_id: "6761b017c29ba495edcbe5e1",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 4342318,
            known_for_department: "Acting",
            name: "印第安娜·艾尔",
            original_name: "Indiana Elle",
            popularity: 1.4931,
            profile_path: "/d9Bk6BWiPmWIx1Ssx36GqReFjQJ.jpg",
            cast_id: 22,
            character: "Cece Winchester",
            credit_id: "6813839de4c08aa248b1fbd3",
            order: 4,
          },
          {
            adult: false,
            gender: 1,
            id: 2035942,
            known_for_department: "Acting",
            name: "萨拉·库珀",
            original_name: "Sarah Cooper",
            popularity: 0.3318,
            profile_path: "/w4mHp7oYUX1kLvdhVj7ASSixCUm.jpg",
            cast_id: 71,
            character: "Pam",
            credit_id: "696982706a248243d627991f",
            order: 5,
          },
          {
            adult: false,
            gender: 1,
            id: 20,
            known_for_department: "Acting",
            name: "伊丽莎白·帕金斯",
            original_name: "Elizabeth Perkins",
            popularity: 2.3365,
            profile_path: "/vTWYllD9V76rgv9XAbtkkjjeunG.jpg",
            cast_id: 37,
            character: "Mrs. Winchester",
            credit_id: "693be65ea964adc5bffc47d1",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 2013576,
            known_for_department: "Acting",
            name: "艾伦·塔玛基",
            original_name: "Ellen Tamaki",
            popularity: 0.9131,
            profile_path: "/kQGqxMmGdpGTvBJEy3gWvMf1fKO.jpg",
            cast_id: 19,
            character: "Patrice",
            credit_id: "6813835190ca48915ce81f86",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/gbjK8p5S1aLXWCwOoXqr9aWZvqG.jpg",
      genre_ids: [16, 10751, 35, 12, 14],
      id: 991494,
      original_language: "en",
      original_title: "The SpongeBob Movie: Search for SquarePants",
      overview:
        "海绵宝宝和他的朋友们派大星、章鱼哥、珊迪以及蟹老板前往海洋深处面对飞翔的荷兰人幽灵，遭遇挑战并揭开海洋奥秘。",
      popularity: 163.8148,
      poster_path: "/rE7mi4WfvT1Kc0LxUqpMtYoG26G.jpg",
      release_date: "2025-12-16",
      title: "海绵宝宝：深海大冒险",
      video: false,
      vote_average: 6.4,
      vote_count: 96,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 78798,
            known_for_department: "Acting",
            name: "汤姆·肯尼",
            original_name: "Tom Kenny",
            popularity: 2.7259,
            profile_path: "/dKOxpGnRkIMaPkZSHKIns99WxQa.jpg",
            cast_id: 1,
            character: "SpongeBob SquarePants / Gary / Morning DJ (voice)",
            credit_id: "62b51be24f9a9900608b9c66",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 6574,
            known_for_department: "Acting",
            name: "克兰西·布朗",
            original_name: "Clancy Brown",
            popularity: 3.8366,
            profile_path: "/1JeBRNG7VS7r64V9lOvej9bZXW5.jpg",
            cast_id: 5,
            character: "Mr. Krabs / Pirate / Narrator (voice)",
            credit_id: "6476c3481f98d1028471fac8",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 70615,
            known_for_department: "Acting",
            name: "阿尔伯特·邦帕斯",
            original_name: "Rodger Bumpass",
            popularity: 1.2037,
            profile_path: "/lGQkw6adxqB6Hcm7VK8nVHbKupe.jpg",
            cast_id: 4,
            character: "Squidward Tentacles (voice)",
            credit_id: "6476c33512c60400e1dc5f31",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 34398,
            known_for_department: "Acting",
            name: "比尔·法格巴克",
            original_name: "Bill Fagerbakke",
            popularity: 1.0339,
            profile_path: "/zntKKc1uT53BnIihmzbq601eWKZ.jpg",
            cast_id: 3,
            character: "Patrick Star (voice)",
            credit_id: "6476c320706b9f00f89908ff",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 78799,
            known_for_department: "Acting",
            name: "卡罗琳·劳伦斯",
            original_name: "Carolyn Lawrence",
            popularity: 0.8115,
            profile_path: "/vHycxQTs8EuyFdFJNww15xXB5lT.jpg",
            cast_id: 13,
            character: "Sandy Cheeks (voice)",
            credit_id: "66d4c0e0147f47aa6a658dd9",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 188229,
            known_for_department: "Acting",
            name: "劳伦斯先生",
            original_name: "Mr. Lawrence",
            popularity: 1.3401,
            profile_path: "/gWFgxlREzbaPPdWsQZSCdjrFozy.jpg",
            cast_id: 14,
            character: "Sheldon J. Plankton (voice)",
            credit_id: "66d4c0f2ee1ec0f10cc0fb94",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 41798,
            known_for_department: "Acting",
            name: "乔治·洛佩兹",
            original_name: "George López",
            popularity: 1.3175,
            profile_path: "/jeUUeE3ipY9edqdOSNI9v5maAbi.jpg",
            cast_id: 40,
            character: "JK Fishlips (voice)",
            credit_id: "684849d09ae1425b31206b25",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 4118330,
            known_for_department: "Acting",
            name: "Ice Spice",
            original_name: "Ice Spice",
            popularity: 0.693,
            profile_path: "/q3O02uHVOWd6Qoa5uNQmXlpLEpj.jpg",
            cast_id: 41,
            character: "Ticket Taker (voice)",
            credit_id: "684849da5cbe141884bb3801",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/ykigHs1OIyqqV04zfFqIlSHp546.jpg",
      genre_ids: [53, 27, 28, 9648, 878],
      id: 1412598,
      original_language: "en",
      original_title: "Killer Whale",
      overview:
        "故事围绕一对挚友Trish Stevens与Maddie Clark展开，二人被困在一座与世隔绝的环礁湖里，与一头危险的虎鲸狭路相逢。",
      popularity: 143.6977,
      poster_path: "/7BkmHVHbXcQVjfQQIxqjIr05IWe.jpg",
      release_date: "2026-01-16",
      title: "杀人鲸",
      video: false,
      vote_average: 5.574,
      vote_count: 34,
      credits: {
        cast: [
          {
            adult: false,
            gender: 1,
            id: 1279279,
            known_for_department: "Acting",
            name: "弗吉尼亚·加德纳",
            original_name: "Virginia Gardner",
            popularity: 2.3305,
            profile_path: "/wD0Ib0AqzfIxBL9X0x8YDbKoI2E.jpg",
            cast_id: 12,
            character: "Maddie",
            credit_id: "6779fa75816b2810d166d4b5",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 2637828,
            known_for_department: "Acting",
            name: "Melanie Jarnson",
            original_name: "Melanie Jarnson",
            popularity: 1.4846,
            profile_path: "/8m0gnlADmLXkMkvSzDR2OhBfsCB.jpg",
            cast_id: 13,
            character: "Trish",
            credit_id: "6779fa87eca85bd5087267fd",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 1421393,
            known_for_department: "Acting",
            name: "Mitchell Hope",
            original_name: "Mitchell Hope",
            popularity: 0.9628,
            profile_path: "/oENPvMMblZYzEd4tGJ6VGaxsg6q.jpg",
            cast_id: 14,
            character: "Josh",
            credit_id: "6779fa93816b2810d166d4cc",
            order: 2,
          },
          {
            adult: false,
            gender: 0,
            id: 2387468,
            known_for_department: "Acting",
            name: "Isaac Crawley",
            original_name: "Isaac Crawley",
            popularity: 0.2556,
            profile_path: "/c4mZLQ0rtGSgWE3ciqepvSQoEA2.jpg",
            cast_id: 15,
            character: "Chad",
            credit_id: "6779fa9dab5ec4c3dc729ad0",
            order: 3,
          },
          {
            adult: false,
            gender: 0,
            id: 4066265,
            known_for_department: "Crew",
            name: "Scott James George",
            original_name: "Scott James George",
            popularity: 0.1188,
            profile_path: "/4SaTqCO3tOqbkrcsPEbt8SEKtC.jpg",
            cast_id: 16,
            character: "Hooded Man",
            credit_id: "681097f82e8ba022e480de56",
            order: 4,
          },
          {
            adult: false,
            gender: 0,
            id: 1250583,
            known_for_department: "Acting",
            name: "Luke Cunningham",
            original_name: "Luke Cunningham",
            popularity: 0.0814,
            profile_path: null,
            cast_id: 32,
            character: "Waiter",
            credit_id: "696d961b695591492c20d601",
            order: 5,
          },
          {
            adult: false,
            gender: 0,
            id: 4001408,
            known_for_department: "Acting",
            name: "Anna Yen",
            original_name: "Anna Yen",
            popularity: 0.1575,
            profile_path: null,
            cast_id: 33,
            character: "Market Lady",
            credit_id: "696d96433ebcc624947fa5bf",
            order: 6,
          },
          {
            adult: false,
            gender: 0,
            id: 1205489,
            known_for_department: "Acting",
            name: "Shinji Ikefuji",
            original_name: "Shinji Ikefuji",
            popularity: 0.2288,
            profile_path: "/xq6gkUWJOZjTSJpcD6hXIexITay.jpg",
            cast_id: 34,
            character: "Cleaner",
            credit_id: "696d967d6949af49cd7fa617",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      genre_ids: [16, 28, 14],
      id: 1311031,
      original_language: "ja",
      original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      overview:
        "当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞辻无惨在产屋敷宅邸出现。由于鬼杀队的主公处于危险之中，炭治郎和柱急忙赶往总部，但却被鸣女推入一个神秘的异空间。炭治郎和鬼杀队的目标是鬼的堡垒——无限城。因此，鬼杀队和鬼之间的最终战斗的战场已经准备就绪。",
      popularity: 107.5916,
      poster_path: "/bhIytk0hlaHmGrQFY9P7bWhZZfC.jpg",
      release_date: "2025-07-18",
      title: "鬼灭之刃：无限城篇 第一章 猗窝座再袭",
      video: false,
      vote_average: 7.67,
      vote_count: 676,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 1256603,
            known_for_department: "Acting",
            name: "花江夏树",
            original_name: "花江夏樹",
            popularity: 1.7424,
            profile_path: "/alTb0DlcPIbcwM08WSmxFai58sd.jpg",
            cast_id: 2,
            character: "Tanjiro Kamado (voice)",
            credit_id: "66e6e105e8211ecd22b08a62",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 9705,
            known_for_department: "Acting",
            name: "樱井孝宏",
            original_name: "櫻井孝宏",
            popularity: 3.2756,
            profile_path: "/8s8owcKmpRAuhzEGjSdRpztthUg.jpg",
            cast_id: 25,
            character: "Giyu Tomioka (voice)",
            credit_id: "67cec4fba8b335257e2aa988",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 81244,
            known_for_department: "Acting",
            name: "石田彰",
            original_name: "石田彰",
            popularity: 2.5718,
            profile_path: "/jnW2Gn2NlR2uwOCeyOuzypnTmkH.jpg",
            cast_id: 336,
            character: "Akaza (voice)",
            credit_id: "687d4a14807abd7583d98d45",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 119145,
            known_for_department: "Acting",
            name: "下野纮",
            original_name: "下野紘",
            popularity: 2.1617,
            profile_path: "/yrSDcgFefHtWkFmLnTrcw2t0MV.jpg",
            cast_id: 1,
            character: "Zenitsu Agatsuma (voice)",
            credit_id: "66e6e0e8050f14e4fccf8130",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 1253008,
            known_for_department: "Acting",
            name: "细谷佳正",
            original_name: "細谷佳正",
            popularity: 1.6174,
            profile_path: "/lUR5oN1LrqGgp25IOcI1qOH1Ud5.jpg",
            cast_id: 360,
            character: "Kaigaku (voice)",
            credit_id: "68cb2d1c1901469ad3e4fefe",
            order: 4,
          },
          {
            adult: false,
            gender: 1,
            id: 221773,
            known_for_department: "Acting",
            name: "早见沙织",
            original_name: "早見沙織",
            popularity: 2.4186,
            profile_path: "/gLv9lO7dlUbIsmyJUvgegqAAXki.jpg",
            cast_id: 28,
            character: "Shinobu Kocho (voice)",
            credit_id: "67cec51fa8b335257e2aa9b0",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 93803,
            known_for_department: "Acting",
            name: "宫野真守",
            original_name: "宮野真守",
            popularity: 1.9498,
            profile_path: "/nuok8ueG7k9hPZ09Tpr8e7Qn0ah.jpg",
            cast_id: 357,
            character: "Doma (voice)",
            credit_id: "68c595f12d948a0fc4acad8a",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 1452028,
            known_for_department: "Acting",
            name: "上田丽奈",
            original_name: "上田麗奈",
            popularity: 1.8904,
            profile_path: "/cddK6dQtVCg6ToQRpETbRYRJK4G.jpg",
            cast_id: 23,
            character: "Kanao Tsuyuri (voice)",
            credit_id: "67cec4ba53282c9de62a757c",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/dT1p0K1szMAUBuE2bibouDQdNb8.jpg",
      genre_ids: [27, 53, 878],
      id: 1272837,
      original_language: "en",
      original_title: "28 Years Later: The Bone Temple",
      overview:
        "末日丧钟再度敲响，带领观众直视人性毁灭的炼狱，感染者的威胁和幸存人类的邪恶。",
      popularity: 94.8802,
      poster_path: "/rLsxpg09Y7E1G0h3vX4frr0yh1D.jpg",
      release_date: "2026-01-14",
      title: "惊变28年2：白骨圣殿",
      video: false,
      vote_average: 7.2,
      vote_count: 204,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 5469,
            known_for_department: "Acting",
            name: "拉尔夫·费因斯",
            original_name: "Ralph Fiennes",
            popularity: 5.8588,
            profile_path: "/u29BOqiV5GCQ8k8WUJM50i9xlBf.jpg",
            cast_id: 23,
            character: "Dr. Ian Kelson",
            credit_id: "68544ccf359cd94d7b77d129",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 85065,
            known_for_department: "Acting",
            name: "杰克·奥康奈尔",
            original_name: "Jack O'Connell",
            popularity: 7.9663,
            profile_path: "/9RrqnB1BRaWWHEjlWVVAna0sdBB.jpg",
            cast_id: 19,
            character: "Sir Lord Jimmy Crystal",
            credit_id: "6837af21f3c16643464155be",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 5107934,
            known_for_department: "Acting",
            name: "Alfie Williams",
            original_name: "Alfie Williams",
            popularity: 1.7162,
            profile_path: "/wqfyAhZH6uCu5J4THsz2gJxsizB.jpg",
            cast_id: 22,
            character: "Spike",
            credit_id: "6853e59d1e28ff816977cfa2",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 1672504,
            known_for_department: "Acting",
            name: "艾琳·凯利曼",
            original_name: "Erin Kellyman",
            popularity: 1.7956,
            profile_path: "/f7XXomAaSRxE3h5NT0sAlcQTjPL.jpg",
            cast_id: 25,
            character: "Jimmy Ink",
            credit_id: "68544d1b179d1704bf5d8a90",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 1344320,
            known_for_department: "Acting",
            name: "Chi Lewis-Parry",
            original_name: "Chi Lewis-Parry",
            popularity: 10.7938,
            profile_path: "/yFE1xHcKn9Gww9DCUYQmBlZ3HVx.jpg",
            cast_id: 30,
            character: "Samson",
            credit_id: "68811b271db2322db038e679",
            order: 4,
          },
          {
            adult: false,
            gender: 1,
            id: 2290611,
            known_for_department: "Acting",
            name: "艾玛·莱尔德",
            original_name: "Emma Laird",
            popularity: 2.6434,
            profile_path: "/lcsyb7KZUcg8LRBkiCJScYD2rYT.jpg",
            cast_id: 20,
            character: "Jimmima",
            credit_id: "6837af41cc484ff60deb43c0",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 5518922,
            known_for_department: "Acting",
            name: "Connor Newall",
            original_name: "Connor Newall",
            popularity: 0.2678,
            profile_path: "/tH5BfF7KwpfME997B0pZ57Bfi6h.jpg",
            cast_id: 29,
            character: "Jimmy Shite",
            credit_id: "6856ad62656691ce18cb4849",
            order: 6,
          },
          {
            adult: false,
            gender: 0,
            id: 5514148,
            known_for_department: "Acting",
            name: "Maura Bird",
            original_name: "Maura Bird",
            popularity: 0.2457,
            profile_path: "/kuQCb4Nhe0xEE4LqanGAizuCAGR.jpg",
            cast_id: 24,
            character: "Jimmy Jones",
            credit_id: "68544d00ce04ec5da1ecaab4",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 1419406,
      original_language: "zh",
      original_title: "捕风追影",
      overview:
        "一伙天才盗匪劫走数亿资产，却凭借超强反侦察能力全身而退，戏耍警方“天眼”系统。一筹莫展之际，澳门司警局请回了隐退多年的跟踪专家黄德忠（成龙 饰），他培养年轻司警何秋果（张子枫 饰）等人，重组“神秘跟踪队”，最终锁定了盗匪团的幕后狼王傅隆生（梁家辉 饰）。当警方布下天罗地网之时，盗匪团也设下局中局，斗智斗勇斗心眼，一场高端猫鼠局拉开帷幕……",
      popularity: 91.97,
      poster_path: "/o25Tk1FYQi2BLk0OEAvx2h69QvB.jpg",
      release_date: "2025-08-16",
      title: "捕风追影",
      video: false,
      vote_average: 7.159,
      vote_count: 324,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 18897,
            known_for_department: "Acting",
            name: "成龙",
            original_name: "成龍",
            popularity: 18.2738,
            profile_path: "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
            cast_id: 3,
            character: "Huang Dezhong",
            credit_id: "678b57d08bca661d0542feab",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 1173805,
            known_for_department: "Acting",
            name: "张子枫",
            original_name: "张子枫",
            popularity: 2.7668,
            profile_path: "/3S8yEnTVqH8T3bTVf9FmtXxWcu2.jpg",
            cast_id: 4,
            character: "He Qiuguo",
            credit_id: "678b57d7e4566399a26dc271",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 56861,
            known_for_department: "Acting",
            name: "梁家辉",
            original_name: "梁家輝",
            popularity: 2.2625,
            profile_path: "/n5XtznlOfGSfYvckuxCiTapG4tB.jpg",
            cast_id: 5,
            character: "Fu Longsheng",
            credit_id: "678b57ff1afc34646764e327",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 3167855,
            known_for_department: "Acting",
            name: "此沙",
            original_name: "此沙",
            popularity: 3.1259,
            profile_path: "/eWytg5M0VUCb0aHEKpUDijQ7JxF.jpg",
            cast_id: 6,
            character: "Xi Meng / Xi Wang",
            credit_id: "678b5808859fb4e6a86dc899",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 1625880,
            known_for_department: "Acting",
            name: "文俊辉",
            original_name: "文俊辉",
            popularity: 1.6797,
            profile_path: "/z1seXrQQWG7nsQVHqSWKefJQ8DO.jpg",
            cast_id: 7,
            character: "Hu Feng",
            credit_id: "678b581842f27c754c64e1d0",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 4062369,
            known_for_department: "Acting",
            name: "周政杰",
            original_name: "周政杰",
            popularity: 0.5875,
            profile_path: "/9n4vnXt6SIrfUfDDXxz4ewxhbSf.jpg",
            cast_id: 8,
            character: "Liu Jinxiao",
            credit_id: "678b58698bca661d0542ff2c",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 1016316,
            known_for_department: "Acting",
            name: "王杍逸",
            original_name: "王杍逸",
            popularity: 0.9573,
            profile_path: "/6xOEI8NnQuvRwe6nSDXYGAamKzO.jpg",
            cast_id: 9,
            character: "Wu Yaolei",
            credit_id: "678b58748bca661d0542ff41",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 1516593,
            known_for_department: "Acting",
            name: "郎月婷",
            original_name: "郎月婷",
            popularity: 1.0109,
            profile_path: "/bdyJhQrIG7ai9B2Tp2kD2M0F32X.jpg",
            cast_id: 10,
            character: "Wang Xuemei",
            credit_id: "678b587d42f27c754c64e208",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/kHHVzOGE23kavlvFOxeHaBmrgBJ.jpg",
      genre_ids: [18],
      id: 1317288,
      original_language: "en",
      original_title: "Marty Supreme",
      overview:
        "为了实现一个无人相信的伟大梦想，马蒂去了一趟地狱。年轻迷人的马蒂，渴望名声、荣耀，以及遥不可及的“世界乒乓球冠军”头衔。为了梦想，他什么都能做到。穿越纽约、巴黎、伦敦、开罗与东京，他在无数的挫折与考验中前行，遇见了挚友、恋人与伙伴，也一次次在胜败之间重生。最终，他开创了自己的伟大道路，也领悟了荣光的真正意义。",
      popularity: 74.2056,
      poster_path: "/sGaiYUhrGWCCBMawmr3rRtq92O4.jpg",
      release_date: "2025-12-19",
      title: "至尊马蒂",
      video: false,
      vote_average: 8,
      vote_count: 187,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 1190668,
            known_for_department: "Acting",
            name: "提莫西·查拉梅",
            original_name: "Timothée Chalamet",
            popularity: 9.3588,
            profile_path: "/dFxpwRpmzpVfP1zjluH68DeQhyj.jpg",
            cast_id: 1,
            character: "Marty Mauser",
            credit_id: "6695720a5e16b675278ccc18",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 12052,
            known_for_department: "Acting",
            name: "格温妮斯·帕特洛",
            original_name: "Gwyneth Paltrow",
            popularity: 2.9593,
            profile_path: "/8x3jpWD7DEvyMXO1FOjwNdd1UZT.jpg",
            cast_id: 11,
            character: "Kay Stone",
            credit_id: "66cf623c5b362ecb33ec310e",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 1972166,
            known_for_department: "Acting",
            name: "奥德萨·阿兹恩",
            original_name: "Odessa A'zion",
            popularity: 4.1578,
            profile_path: "/fGgP2Ik5PbWlDVQNp6SN8oPsu0P.jpg",
            cast_id: 13,
            character: "Rachel Mizler",
            credit_id: "66eb18b51beca8ce07d3a439",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 1240877,
            known_for_department: "Acting",
            name: "Kevin O'Leary",
            original_name: "Kevin O'Leary",
            popularity: 0.6488,
            profile_path: "/uvTv976u2wgrl9RqxSfBeTlE1Wz.jpg",
            cast_id: 14,
            character: "Milton Rockwell",
            credit_id: "66eb1ac35c0519a234d38f81",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 39104,
            known_for_department: "Directing",
            name: "Abel Ferrara",
            original_name: "Abel Ferrara",
            popularity: 0.7544,
            profile_path: "/wdOxXWyxE3HjrtdeOJvc9xB5eUv.jpg",
            cast_id: 16,
            character: "Ezra Mishkin",
            credit_id: "66eb1d7c1beca8ce07d3a86d",
            order: 4,
          },
          {
            adult: false,
            gender: 1,
            id: 53122,
            known_for_department: "Acting",
            name: "弗朗辛·德雷舍尔",
            original_name: "Fran Drescher",
            popularity: 1.6957,
            profile_path: "/kQzvZ4ksLunfs3QZQtzRhzLJPBY.jpg",
            cast_id: 25,
            character: "Rebecca Mauser",
            credit_id: "66fff66cf878adfed0852712",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 1133834,
            known_for_department: "Acting",
            name: "Tyler, The Creator",
            original_name: "Tyler, The Creator",
            popularity: 0.9847,
            profile_path: "/jdAYV2hhjsffcRBTPqCMzHLIiM1.jpg",
            cast_id: 12,
            character: "Wally",
            credit_id: "66e880e0050f14e4fcd0282b",
            order: 6,
          },
          {
            adult: false,
            gender: 2,
            id: 1041440,
            known_for_department: "Acting",
            name: "埃默里·科恩",
            original_name: "Emory Cohen",
            popularity: 2.0197,
            profile_path: "/mtummZcNxmcJQ1JIoQUcV3Fwb3.jpg",
            cast_id: 148,
            character: "Ira Mizler",
            credit_id: "6913589e119eef2e209acdfd",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/ncI1PlBcANixIkgQSnjsSRz4OyT.jpg",
      genre_ids: [28, 53, 9648],
      id: 1439112,
      original_language: "en",
      original_title: "Muzzle: City of Wolves",
      overview:
        "　　杰克·罗瑟曾是一名警犬训导员，因服役期间的创伤后应激障碍（PTSD）而饱受折磨，如今他努力与家人及退役警犬伙伴过着平静安宁的生活。然而，一场残酷的暴力袭击瞬间打破了这份宁静——一个残忍无情的帮派将他们锁定为目标。为了保护所爱之人，杰克与他的新警犬搭档“阿戈斯”深入罪恶滋生的黑暗世界，在那里，他不仅要面对腐败官员、揭开危险的毒品走私网络，更要直面自己内心的恶魔。",
      popularity: 63.2386,
      poster_path: "/8qTMRmC07XCGidnKQFLbRM3FoDU.jpg",
      release_date: "2025-11-13",
      title: "神探忠犬：狼之城",
      video: false,
      vote_average: 6.742,
      vote_count: 97,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 6383,
            known_for_department: "Acting",
            name: "艾伦·艾克哈特",
            original_name: "Aaron Eckhart",
            popularity: 2.5132,
            profile_path: "/u5JjnRMr9zKEVvOP7k3F6gdcwT6.jpg",
            cast_id: 23,
            character: "Jake Rosser",
            credit_id: "67bc291ae5fd18f7b6464497",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 1139816,
            known_for_department: "Acting",
            name: "坦娅·范·格拉恩",
            original_name: "Tanya van Graan",
            popularity: 0.6448,
            profile_path: "/xeTvZH86esj3tuErPv0relTqPOY.jpg",
            cast_id: 24,
            character: "Mia Rosser",
            credit_id: "67bc292c8505082993be9c01",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 209193,
            known_for_department: "Acting",
            name: "Karl Thaning",
            original_name: "Karl Thaning",
            popularity: 0.2675,
            profile_path: "/oOrTV9OvC5H1BlRosJcdxWlYWW5.jpg",
            cast_id: 25,
            character: "Officer Beekman",
            credit_id: "67bc293784e930a0210ab8e6",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 1658759,
            known_for_department: "Acting",
            name: "Nicole Fortuin",
            original_name: "Nicole Fortuin",
            popularity: 0.3434,
            profile_path: "/6YxW3hZANTmhrESXIdFtqvfIjtq.jpg",
            cast_id: 26,
            character: "Detective Idalia Cutler",
            credit_id: "67bc296c515c9e42af0a6975",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 85780,
            known_for_department: "Acting",
            name: "阿德里安·柯林斯",
            original_name: "Adrian Collins",
            popularity: 0.4049,
            profile_path: "/3ROguAf0SqpnrA5gJ3MkdL6Yxab.jpg",
            cast_id: 35,
            character: "Officer Cobb",
            credit_id: "69188a3164907fabe331d3f3",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 2603,
            known_for_department: "Acting",
            name: "Hakeem Kae-Kazim",
            original_name: "Hakeem Kae-Kazim",
            popularity: 0.7049,
            profile_path: "/sVNHRm51c9toG73FUQ5k1St0vju.jpg",
            cast_id: 41,
            character: "Detective Thorne",
            credit_id: "693e61303ecd860338f78618",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 1187374,
            known_for_department: "Acting",
            name: "Bongo Mbutuma",
            original_name: "Bongo Mbutuma",
            popularity: 0.1901,
            profile_path: "/jByYhcxIlAdEqpGnHiLzGXsTJ2b.jpg",
            cast_id: 42,
            character: "Officer Brown",
            credit_id: "693e61f33580b58373999554",
            order: 6,
          },
          {
            adult: false,
            gender: 2,
            id: 2669277,
            known_for_department: "Acting",
            name: "Grant Ross",
            original_name: "Grant Ross",
            popularity: 0.1741,
            profile_path: "/6iC4C3zWwgxJ0jih2ximj12VbZn.jpg",
            cast_id: 34,
            character: "Detective Spitzer",
            credit_id: "691889ec70048d82ec9ae1bb",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/ufuabtiOem0kHeYz6b8x8MjBb2L.jpg",
      genre_ids: [35, 18],
      id: 1208348,
      original_language: "en",
      original_title: "Rental Family",
      overview:
        "本片讲述了一位在东京落魄的美国演员的故事。他受雇于一家日本家庭租赁公司，充当门面上的“美籍演员”，由此通过扮演他人生活中的各种角色，踏上了一段意想不到的自我发现之旅。",
      popularity: 51.8455,
      poster_path: "/msX6Gv6MzP9IMbuV6XbUC9U2xCu.jpg",
      release_date: "2025-11-20",
      title: "临租家庭",
      video: false,
      vote_average: 7.749,
      vote_count: 231,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 18269,
            known_for_department: "Acting",
            name: "布兰登·费舍",
            original_name: "Brendan Fraser",
            popularity: 4.1594,
            profile_path: "/tFj5PaWWQbb8rHBBhu1EHklznph.jpg",
            cast_id: 10,
            character: "Phillip Vanderploeg",
            credit_id: "655d04bf7f054018d421c411",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 1082509,
            known_for_department: "Acting",
            name: "平岳大平",
            original_name: "平岳大",
            popularity: 1.2697,
            profile_path: "/2N1viBfPY4cRlz6W6YfM2F6UbSH.jpg",
            cast_id: 12,
            character: "Shinji",
            credit_id: "65f8d34233a376014635612e",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 2210389,
            known_for_department: "Acting",
            name: "玛丽·亚马莫托",
            original_name: "Mari Yamamoto",
            popularity: 1.6092,
            profile_path: "/chy8WQgbSfIxp4B1lHzHFFVzsEv.jpg",
            cast_id: 11,
            character: "Aiko",
            credit_id: "65e74f4509dda40162be11c9",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 5615231,
            known_for_department: "Acting",
            name: "香农·戈尔曼",
            original_name: "Shannon Mahina Gorman",
            popularity: 1.1609,
            profile_path: "/8t3tWp0K8eMrnMBrZYTZibaKSPS.jpg",
            cast_id: 23,
            character: "Mia Kawasaki",
            credit_id: "68969b3c37eb97ec74b6f5b0",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 13283,
            known_for_department: "Acting",
            name: "柄本明",
            original_name: "柄本明",
            popularity: 1.4147,
            profile_path: "/qQHdGgAL7idxy79oWHjYON6bYQm.jpg",
            cast_id: 13,
            character: "Kikuo Hasegawa",
            credit_id: "65f8d359391b9c0148c7b4ab",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 3549285,
            known_for_department: "Acting",
            name: "保罗·安德里亚·迪·皮耶特罗",
            original_name: "Paolo Andrea Di Pietro",
            popularity: 0.3279,
            profile_path: "/pnsPTQv0k6GVxRjgnBGVLUwOgci.jpg",
            cast_id: 30,
            character: "Handsome Actor",
            credit_id: "68c6415575ce32d37921fe85",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 1264679,
            known_for_department: "Acting",
            name: "尾関伸嗣",
            original_name: "尾関伸嗣",
            popularity: 0.7242,
            profile_path: "/7KyN7b1ocVswsU2IhCLRNz3aYTU.jpg",
            cast_id: 31,
            character: "Casting Director",
            credit_id: "68c6416dec3ac8c8a1230b24",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 4829074,
            known_for_department: "Acting",
            name: "Shino Shinozaki",
            original_name: "Shino Shinozaki",
            popularity: 0.1727,
            profile_path: null,
            cast_id: 38,
            character: "Hitomi Kawasaki",
            credit_id: "68c7e346443932a125220a7d",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/eeGRpU64sIrRApjWXvTpK5Lep2K.jpg",
      genre_ids: [80, 18, 53],
      id: 1220564,
      original_language: "pt",
      original_title: "O Agente Secreto",
      overview:
        "1977年，巴西。四十岁出头的技术专家马塞洛正在奔逃。他在狂欢节期间抵达累西腓，渴望与儿子重聚，却很快意识到这座城市远非他寻求的非暴力庇护所。",
      popularity: 59.4194,
      poster_path: "/ptMhBAOi5La3NYLX2nWQFMzkXVL.jpg",
      release_date: "2025-07-23",
      title: "密探",
      video: false,
      vote_average: 7.686,
      vote_count: 199,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 52583,
            known_for_department: "Acting",
            name: "瓦格纳·马拉",
            original_name: "Wagner Moura",
            popularity: 6.2074,
            profile_path: "/yJjV1ZCQbCSSgRy05FncCKjyaY4.jpg",
            cast_id: 2,
            character: "Armando / Marcelo / Adult Fernando",
            credit_id: "65830fcb55bc35571517cc12",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 2346588,
            known_for_department: "Acting",
            name: "Carlos Francisco",
            original_name: "Carlos Francisco",
            popularity: 0.5051,
            profile_path: "/ihf4bN4GuScyA2QwlzVCnPqOuOo.jpg",
            cast_id: 30,
            character: "Seu Alexandre",
            credit_id: "67f7a4cb31775276d6d983a7",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 4497686,
            known_for_department: "Acting",
            name: "Tânia Maria",
            original_name: "Tânia Maria",
            popularity: 0.4759,
            profile_path: "/73QyA2htiMJ01sFo25KLCDyPtWF.jpg",
            cast_id: 62,
            character: "Dona Sebastiana",
            credit_id: "67fa29961bc639566ada908f",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 2375667,
            known_for_department: "Acting",
            name: "Robério Diógenes",
            original_name: "Robério Diógenes",
            popularity: 0.0932,
            profile_path: "/fUFiBSrMmZsBC7ngfBwpTKUhoUl.jpg",
            cast_id: 26,
            character: "Euclides",
            credit_id: "67f7a480ea80d85175995f50",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 143500,
            known_for_department: "Acting",
            name: "Roney Villela",
            original_name: "Roney Villela",
            popularity: 0.4147,
            profile_path: "/y0S7k8ahQF8FAJ0ZCzK2BfTKbz0.jpg",
            cast_id: 29,
            character: "Augusto",
            credit_id: "67f7a4b3ea80d85175995f69",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 1475555,
            known_for_department: "Acting",
            name: "加布里埃尔·莱昂内",
            original_name: "Gabriel Leone",
            popularity: 1.114,
            profile_path: "/iDitSb1sYnHVVguwMqb7EXWmJ61.jpg",
            cast_id: 13,
            character: "Bobbi",
            credit_id: "66a144462de1baaac35daf6f",
            order: 5,
          },
          {
            adult: false,
            gender: 1,
            id: 2652283,
            known_for_department: "Acting",
            name: "Alice Carvalho",
            original_name: "Alice Carvalho",
            popularity: 0.8179,
            profile_path: "/xj2BDbWC0ECOlT3tBaIG0su74Ea.jpg",
            cast_id: 4,
            character: "Fátima",
            credit_id: "666f5f8cfe5e87485e236eb9",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 583446,
            known_for_department: "Acting",
            name: "Hermila Guedes",
            original_name: "Hermila Guedes",
            popularity: 0.7779,
            profile_path: "/dJJh7sekL9dl77tviU5yEVXa1qo.jpg",
            cast_id: 23,
            character: "Claudia",
            credit_id: "66c52b7c7a321deaccaf3b5f",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/4mZ06VpfpAPuaUPn1SEV0brbbxe.jpg",
      genre_ids: [878, 28, 27],
      id: 1196067,
      original_language: "en",
      original_title: "Worldbreaker",
      overview:
        "五年前，现实的裂缝将来自异次元的生物带到了我们的世界，它们一心想要毁灭我们。一位父亲将女儿藏在一座孤岛上，保护她的安全，并教她如何生存，如何面对即将到来的战斗。然而，当世界即将崩塌之时，没有哪个地方是安全的。",
      popularity: 53.4056,
      poster_path: "/kjWZGAqLDJnk97rP3O6kW0KqnIE.jpg",
      release_date: "2025-10-30",
      title: "世界毁灭者",
      video: false,
      vote_average: 6.2,
      vote_count: 61,
      credits: {
        cast: [
          {
            adult: false,
            gender: 1,
            id: 63,
            known_for_department: "Acting",
            name: "米拉·乔沃维奇",
            original_name: "Milla Jovovich",
            popularity: 4.728,
            profile_path: "/usWnHCzbADijULREZYSJ0qfM00y.jpg",
            cast_id: 9,
            character: "Mom",
            credit_id: "6948a12186c6d003b67ac18c",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 114019,
            known_for_department: "Acting",
            name: "卢克·伊万斯",
            original_name: "Luke Evans",
            popularity: 2.3929,
            profile_path: "/qUkYJcrDc4M0LHNYASs30luFvw0.jpg",
            cast_id: 10,
            character: "Dad",
            credit_id: "6948a12a89e2aa8f550734e9",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 2667928,
            known_for_department: "Acting",
            name: "Billie Boullet",
            original_name: "Billie Boullet",
            popularity: 0.3363,
            profile_path: "/x6Xs4CFBiYzBP6zP7uElmtyx1b5.jpg",
            cast_id: 22,
            character: "Willa",
            credit_id: "694f69574d7877550afb1061",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 956385,
            known_for_department: "Acting",
            name: "梅多·威廉姆斯",
            original_name: "Meadow Williams",
            popularity: 0.7416,
            profile_path: "/iECIpEM4BWt94kvOMKFJqv5uJEU.jpg",
            cast_id: 11,
            character: "Soldier #1",
            credit_id: "6948a13753a825795c1553b9",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 3214361,
            known_for_department: "Acting",
            name: "米拉·哈里斯",
            original_name: "Mila Harris",
            popularity: 0.506,
            profile_path: "/10BSVhLPqosSBsOgp0L7qaU0Uhi.jpg",
            cast_id: 12,
            character: "Rosie",
            credit_id: "6948a14089e2aa8f550734ee",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 5287221,
            known_for_department: "Acting",
            name: "Kevin Glynn",
            original_name: "Kevin Glynn",
            popularity: 0.1079,
            profile_path: "/jIQk6lFQ0FOg5piKabufRHfSxNc.jpg",
            cast_id: 14,
            character: "The Man",
            credit_id: "6948a15ea79d0063cd7ac15e",
            order: 5,
          },
          {
            adult: false,
            gender: 0,
            id: 2412148,
            known_for_department: "Acting",
            name: "Chris Finlayson",
            original_name: "Chris Finlayson",
            popularity: 0.1182,
            profile_path: null,
            cast_id: 15,
            character: "Kodiak",
            credit_id: "6948a16fa1b37fcb9ab1cb37",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 3623343,
            known_for_department: "Acting",
            name: "Charis Agbonlahor",
            original_name: "Charis Agbonlahor",
            popularity: 0.1218,
            profile_path: "/88oT1GWOdX64qqJnl247TsL5WG8.jpg",
            cast_id: 16,
            character: "Evac Soldier",
            credit_id: "6948a17f4671fb7c99b1cacf",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/mHC8tSRYfAKGh2jaSNQMSzGdbOW.jpg",
      genre_ids: [878, 28, 53],
      id: 1236153,
      original_language: "en",
      original_title: "Mercy",
      overview:
        "背景设定在不久的将来，死罪不断增加，一名侦探（克里斯·帕拉特 Chris Pratt 饰）被指控犯有暴力罪，他被迫证明自己无罪。",
      popularity: 51.1712,
      poster_path: "/36VpRDwRssBlxfX5L4TvArRiVb.jpg",
      release_date: "2026-01-19",
      title: "极限审判",
      video: false,
      vote_average: 6.86,
      vote_count: 25,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 73457,
            known_for_department: "Acting",
            name: "克里斯·帕拉特",
            original_name: "Chris Pratt",
            popularity: 7.2427,
            profile_path: "/cRH6HPAQ98PlOwwEvhYO4CM9lwu.jpg",
            cast_id: 1,
            character: "Chris Raven",
            credit_id: "65b2f204db952d0162dad586",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 933238,
            known_for_department: "Acting",
            name: "丽贝卡·弗格森",
            original_name: "Rebecca Ferguson",
            popularity: 6.7346,
            profile_path: "/lJloTOheuQSirSLXNA3JHsrMNfH.jpg",
            cast_id: 8,
            character: "Judge Maddox",
            credit_id: "65e62b829979d20163b19783",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 3119545,
            known_for_department: "Acting",
            name: "卡莉·瑞斯",
            original_name: "Kali Reis",
            popularity: 1.336,
            profile_path: "/qJcXQKgaq11aNNPPok0m4yfP2Og.jpg",
            cast_id: 9,
            character: "Jacqueline 'Jaq' Diallo",
            credit_id: "660b0ae5c8a5ac017c788ded",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 82809,
            known_for_department: "Acting",
            name: "安娜贝拉·沃丽丝",
            original_name: "Annabelle Wallis",
            popularity: 3.4363,
            profile_path: "/9lqdI8L2Bgj8zWR5l4l0II6GXug.jpg",
            cast_id: 10,
            character: "Nicole Raven (née Martin)",
            credit_id: "660b0b20c8a5ac016377da96",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 1293892,
            known_for_department: "Acting",
            name: "克里斯·沙利文",
            original_name: "Chris Sullivan",
            popularity: 1.0872,
            profile_path: "/gKZ9xSFrDzUPv27iAkMpH6Qf0Sk.jpg",
            cast_id: 12,
            character: "Robert 'Rob' Nelson",
            credit_id: "660ea662a88587017ce9e5f2",
            order: 4,
          },
          {
            adult: false,
            gender: 1,
            id: 1164259,
            known_for_department: "Acting",
            name: "凯莉·罗杰斯",
            original_name: "Kylie Rogers",
            popularity: 1.7637,
            profile_path: "/dBAnJCb2a7H8gukcP7PqyBRGOUM.jpg",
            cast_id: 14,
            character: "Britt Raven",
            credit_id: "660ea677e18e3f017da4219c",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 1583044,
            known_for_department: "Acting",
            name: "Jeff Pierre",
            original_name: "Jeff Pierre",
            popularity: 0.6837,
            profile_path: "/mKaKc7dviX6q0d7EJpzyHgtdBC7.jpg",
            cast_id: 58,
            character: "Patrick Burke",
            credit_id: "696faee008c80e2262abd1e9",
            order: 6,
          },
          {
            adult: false,
            gender: 2,
            id: 21660,
            known_for_department: "Acting",
            name: "拉菲·加夫隆",
            original_name: "Rafi Gavron",
            popularity: 0.8305,
            profile_path: "/avCWoO9fLwEhbT6cvu0TJcSj49g.jpg",
            cast_id: 11,
            character: "Holt Charles",
            credit_id: "660ea658e18e3f017da42169",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/wPkU44Zirk9RizHGyK54vpd13MT.jpg",
      genre_ids: [80, 53, 35],
      id: 639988,
      original_language: "ko",
      original_title: "어쩔수가없다",
      overview:
        "一名男子失业数年后，为获得新工作灵光一现想出独特计划：消灭自己的竞争对手。",
      popularity: 48.3703,
      poster_path: "/2OX7FU2x8RVaWH622xVAeCIkYno.jpg",
      release_date: "2025-09-24",
      title: "无可奈何",
      video: false,
      vote_average: 7.75,
      vote_count: 505,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 25002,
            known_for_department: "Acting",
            name: "李炳宪",
            original_name: "이병헌",
            popularity: 4.4376,
            profile_path: "/j7SUd9Qi8iOxgrQGb3nQyEYcXur.jpg",
            cast_id: 6,
            character: "Yoo Man-soo",
            credit_id: "660b6c40e039f1017ce5adf3",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 86889,
            known_for_department: "Acting",
            name: "孙艺珍",
            original_name: "손예진",
            popularity: 2.812,
            profile_path: "/njczzJJnugd9y7p5CF3XW7dcyYK.jpg",
            cast_id: 7,
            character: "Lee Mi-ri",
            credit_id: "660b6c4735818f0162395afd",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 93999,
            known_for_department: "Acting",
            name: "朴熙顺",
            original_name: "박희순",
            popularity: 2.4598,
            profile_path: "/s2SSzvlsSfCPP5EXhCoWUr8970F.jpg",
            cast_id: 16,
            character: "Choi Seon-chul",
            credit_id: "6695db3abf067e0df004d026",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 141548,
            known_for_department: "Acting",
            name: "李星民",
            original_name: "이성민",
            popularity: 0.8932,
            profile_path: "/25NytLwnf40D5Yd8MAYnvhar405.jpg",
            cast_id: 14,
            character: "Gu Bum-mo",
            credit_id: "668364d78e23f301cf179686",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 2084416,
            known_for_department: "Acting",
            name: "廉惠兰",
            original_name: "염혜란",
            popularity: 0.7188,
            profile_path: "/xZxVHnbDdNxF6J8UhwBTkJGNKWx.jpg",
            cast_id: 12,
            character: "Lee A-ra",
            credit_id: "668364c48e23f301cf17967d",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 1248450,
            known_for_department: "Acting",
            name: "车胜元",
            original_name: "차승원",
            popularity: 1.0415,
            profile_path: "/zT9SINDaQylXoRTWMb9OdBjLjLt.jpg",
            cast_id: 15,
            character: "Ko Si-jo",
            credit_id: "6695db32ebcd5d7ded04cb63",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 5646019,
            known_for_department: "Acting",
            name: "김우승",
            original_name: "김우승",
            popularity: 0.1766,
            profile_path: "/uGZ9CT9gBg2o6SbkkgqjnsETvuZ.jpg",
            cast_id: 37,
            character: "Yoo Si-won",
            credit_id: "68ab1e1fb0fe6e4f019dadbc",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 4011201,
            known_for_department: "Acting",
            name: "최소율",
            original_name: "최소율",
            popularity: 0.1964,
            profile_path: "/qnYVMDQW9XBBBAdkUhQtOdrcOm1.jpg",
            cast_id: 33,
            character: "Yoo Ri-won",
            credit_id: "68ab1cd5d2ea43a9739dae0d",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/yo41R39airbREp0PYfG30Ofxtgt.jpg",
      genre_ids: [12, 35, 27],
      id: 1234731,
      original_language: "en",
      original_title: "Anaconda",
      overview:
        "　　一群面临中年危机的朋友前往雨林，打算重拍他们年轻时最喜爱的电影，却意外遭遇自然灾害、巨蟒和凶残罪犯，不得不为生存而殊死搏斗。",
      popularity: 50.5062,
      poster_path: "/hmwPrYslUn9BVkCsxDcaPi0FaHg.jpg",
      release_date: "2025-12-24",
      title: "新狂蟒之灾",
      video: false,
      vote_average: 6,
      vote_count: 169,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 70851,
            known_for_department: "Acting",
            name: "杰克·布莱克",
            original_name: "Jack Black",
            popularity: 6.9383,
            profile_path: "/59IhgCtiWI5yTfzPhsjzg7GjCjm.jpg",
            cast_id: 2,
            character: "Doug McCallister",
            credit_id: "66c67259c42459ace0651a7e",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 22226,
            known_for_department: "Acting",
            name: "保罗·路德",
            original_name: "Paul Rudd",
            popularity: 3.526,
            profile_path: "/6jtwNOLKy0LdsRAKwZqgYMAfd5n.jpg",
            cast_id: 3,
            character: "Ronald Griffin Jr.",
            credit_id: "66c67261c42459ace0651a82",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 18324,
            known_for_department: "Acting",
            name: "斯蒂夫·扎恩",
            original_name: "Steve Zahn",
            popularity: 2.9786,
            profile_path: "/rwrPdKGwXnByxUVMxMf8Y7oswi3.jpg",
            cast_id: 12,
            character: "Kenny Trent",
            credit_id: "678accd7704299ac12864970",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 9030,
            known_for_department: "Acting",
            name: "坦迪·牛顿",
            original_name: "Thandiwe Newton",
            popularity: 3.0992,
            profile_path: "/hZQLvxj7nV7pBrRyWTvWVz1CDi8.jpg",
            cast_id: 11,
            character: "Claire Simons",
            credit_id: "678acccfccfbfb1e0e8647c0",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 1784612,
            known_for_department: "Acting",
            name: "丹妮拉·曼希沃",
            original_name: "Daniela Melchior",
            popularity: 2.068,
            profile_path: "/tjAEB90Sa7DJtyTlDAkzVhPLQin.jpg",
            cast_id: 8,
            character: "Ana Almeida",
            credit_id: "66fb040cf906b98958f1a276",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 87341,
            known_for_department: "Acting",
            name: "赛尔顿·梅罗",
            original_name: "Selton Mello",
            popularity: 1.1958,
            profile_path: "/sBVDTAAEDJuVBTKzVGA0PrqeD17.jpg",
            cast_id: 14,
            character: "Santiago",
            credit_id: "678acce6ccfbfb1e0e8647d3",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 9778,
            known_for_department: "Acting",
            name: "艾斯·库珀",
            original_name: "Ice Cube",
            popularity: 2.0119,
            profile_path: "/2w7Pekf8QJ0WVN76cmhcEfTuEDc.jpg",
            cast_id: 44,
            character: "Ice Cube",
            credit_id: "693f3e4f2cc645e9e15e03f5",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 3126,
            known_for_department: "Acting",
            name: "艾农·斯凯",
            original_name: "Ione Skye",
            popularity: 0.8038,
            profile_path: "/ye8qsi6fn51HW93c7065Jogbh9p.jpg",
            cast_id: 13,
            character: "Malie",
            credit_id: "678acce1ccfbfb1e0e8647cb",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/gtKWn9l32PolrFwCuZQsujEAEoc.jpg",
      genre_ids: [28, 12, 53, 878],
      id: 840464,
      original_language: "en",
      original_title: "Greenland 2: Migration",
      overview:
        "　　由于宇宙中的两颗彗星正面撞击了地球，致使地表生态遭遇毁灭性打击，造成恶劣后果。全人类不得不躲藏在地堡中求得生存。身为科学家的加里蒂带着一家人劫后余生，幸存了下来。虽然他们躲过了第一波的冲击，但是他们所在的地堡中剩余的生活物资逐渐减少，其他幸存的人类也开始蠢蠢欲动。迫于压力这一家人必须离开格陵兰岛的安全掩体，开始踏上危险的旅程。在这一路上他们无奈的发现，整个欧洲已经被毁灭，变成了冰冻荒地。于是一家人只能再次被迫上路……",
      popularity: 46.5276,
      poster_path: "/AnwAqaPQyM4ugJ5V5vtdqylFW4J.jpg",
      release_date: "2026-01-07",
      title: "末日逃生2：迁移",
      video: false,
      vote_average: 6.432,
      vote_count: 73,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 17276,
            known_for_department: "Acting",
            name: "杰拉德·巴特勒",
            original_name: "Gerard Butler",
            popularity: 5.9117,
            profile_path: "/rTO5opVC3Gs6hPYAxWSP9eEjogi.jpg",
            cast_id: 9,
            character: "John Garrity",
            credit_id: "60c7b1f75b4fed00425d4e21",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 54882,
            known_for_department: "Acting",
            name: "莫雷纳·巴卡林",
            original_name: "Morena Baccarin",
            popularity: 10.6577,
            profile_path: "/kBSKKaOtsqIzZPhtEeHfCBmhWl9.jpg",
            cast_id: 10,
            character: "Allison Garrity",
            credit_id: "60c7b205b6c2640058b08cf4",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 1754784,
            known_for_department: "Acting",
            name: "托米·厄尔·詹金斯",
            original_name: "Tommie Earl Jenkins",
            popularity: 0.5072,
            profile_path: "/kl2dzZU3p6pOjuKBi52wOnEGvEp.jpg",
            cast_id: 23,
            character: "General Sharpe",
            credit_id: "66c5896a6d8eef38d7ade2e5",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 85151,
            known_for_department: "Acting",
            name: "斯荣德·福斯·奥瓦格",
            original_name: "Trond Fausa Aurvåg",
            popularity: 0.8952,
            profile_path: "/rFWC22ZScaQwA85NBo7l1j9XQdo.jpg",
            cast_id: 22,
            character: "Adam Shaw",
            credit_id: "66c5894f125f846f00f7381b",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 574378,
            known_for_department: "Acting",
            name: "Amber Rose Revah",
            original_name: "Amber Rose Revah",
            popularity: 1.3203,
            profile_path: "/AjVg1UrGqm0mlbis8CVm0O56Ae2.jpg",
            cast_id: 20,
            character: "Dr Casey Amina",
            credit_id: "66c58924eee42eb770714360",
            order: 4,
          },
          {
            adult: false,
            gender: 1,
            id: 2738818,
            known_for_department: "Acting",
            name: "Gina Gangar",
            original_name: "Gina Gangar",
            popularity: 0.3847,
            profile_path: "/kXKKYAUqhcG49tNt7lcUMC2xne7.jpg",
            cast_id: 31,
            character: "Elizabeth Price",
            credit_id: "66c58a4f12d3eace87af5b7a",
            order: 5,
          },
          {
            adult: false,
            gender: 0,
            id: 2033965,
            known_for_department: "Acting",
            name: "Antonio De Lima",
            original_name: "Antonio De Lima",
            popularity: 0.1589,
            profile_path: null,
            cast_id: 32,
            character: "Charles Williams",
            credit_id: "66c58a6c412d66ceafadeb38",
            order: 6,
          },
          {
            adult: false,
            gender: 2,
            id: 78019,
            known_for_department: "Acting",
            name: "彼得·多卡普",
            original_name: "Peter Polycarpou",
            popularity: 0.3949,
            profile_path: "/2lt53oJXRYt3FGzSvCbQmtVfLN2.jpg",
            cast_id: 55,
            character: "Dr Haugen",
            credit_id: "6918c2ae535cb85e69ac306d",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/aHj7d7wSLqrg5cjAcgHhiGr97Ih.jpg",
      genre_ids: [28, 53, 878],
      id: 798645,
      original_language: "en",
      original_title: "The Running Man",
      overview:
        "在近未来的反乌托邦社会，一档电视真人秀《猎杀游戏》以残酷的生存竞赛霸占收视榜首。参赛者必须在职业杀手的猎杀下存活30天，其中的一举一动皆被实时直播给公众，每多活一天便能累积更高额奖金。本·理查兹为拯救重病女儿而孤注一掷，以“最后希望”的身份踏入这场死亡游戏。",
      popularity: 46.8478,
      poster_path: "/vxleCpULOzkJgszhQWnffPXXXu2.jpg",
      release_date: "2025-11-11",
      title: "猎杀游戏",
      video: false,
      vote_average: 6.792,
      vote_count: 1041,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 83271,
            known_for_department: "Acting",
            name: "格伦·鲍威尔",
            original_name: "Glen Powell",
            popularity: 4.3082,
            profile_path: "/fUnIaJkdgvQTztyR1nLeUceSzly.jpg",
            cast_id: 8,
            character: "Ben Richards",
            credit_id: "6618282484f249014a672608",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 91671,
            known_for_department: "Acting",
            name: "科尔曼·多明戈",
            original_name: "Colman Domingo",
            popularity: 1.9439,
            profile_path: "/2tu6T9ugnf82qIMGVKWSb0dvvq5.jpg",
            cast_id: 39,
            character: "Bobby Thompson",
            credit_id: "6780104a7732209e17bb38ec",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 16851,
            known_for_department: "Acting",
            name: "乔什·布洛林",
            original_name: "Josh Brolin",
            popularity: 5.0484,
            profile_path: "/sX2etBbIkxRaCsATyw5ZpOVMPTD.jpg",
            cast_id: 18,
            character: "Dan Killian",
            credit_id: "67116a6429d8a59e045ed0be",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 3905,
            known_for_department: "Acting",
            name: "威廉·H·梅西",
            original_name: "William H. Macy",
            popularity: 3.5672,
            profile_path: "/hdVEGSrP8qWlJnt0v5vSVcGOjy7.jpg",
            cast_id: 23,
            character: "Molie Jernigan",
            credit_id: "671fd3939ff681d9e0a4acfa",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 72095,
            known_for_department: "Acting",
            name: "李·佩斯",
            original_name: "Lee Pace",
            popularity: 3.2087,
            profile_path: "/hePfTi5HwU9X0eX2sOmHj9I1Ryp.jpg",
            cast_id: 19,
            character: "Evan McCone",
            credit_id: "6712918498f6a758cd54ce90",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 39995,
            known_for_department: "Acting",
            name: "迈克尔·塞拉",
            original_name: "Michael Cera",
            popularity: 2.8007,
            profile_path: "/qjhNKsw0OLyZQgK4srhelBafcCf.jpg",
            cast_id: 21,
            character: "Elton Parrakis",
            credit_id: "671c11662685cb6563c0e4fd",
            order: 5,
          },
          {
            adult: false,
            gender: 1,
            id: 1331023,
            known_for_department: "Acting",
            name: "艾米莉亚·琼斯",
            original_name: "Emilia Jones",
            popularity: 2.2333,
            profile_path: "/rnvwYNLkwur5VYHvbMuFny2aXyM.jpg",
            cast_id: 22,
            character: "Amelia Williams",
            credit_id: "671c1175e833d92ef0602615",
            order: 6,
          },
          {
            adult: false,
            gender: 2,
            id: 1339627,
            known_for_department: "Acting",
            name: "Daniel Ezra",
            original_name: "Daniel Ezra",
            popularity: 1.0537,
            profile_path: "/43AIgx8PEABQKkK08OCJ9239OK6.jpg",
            cast_id: 16,
            character: "Bradley Throckmorton",
            credit_id: "6706b836a88614d6b08b0c9f",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/zWe8ynGlGH3KP896jHCemxnOvCo.jpg",
      genre_ids: [27, 9648],
      id: 680493,
      original_language: "en",
      original_title: "Return to Silent Hill",
      overview:
        "James在与爱人分开后伤心欲绝，而此时，他被一封神秘的信件召唤回了寂静岭去寻找她，却发现自己曾经熟悉的小镇已经被未知的邪恶占据。面对着各种熟悉和陌生的可怕人事物，James开始质疑自己的理智和对现实的认知，但他必须坚持下去，拯救自己失落的爱人。",
      popularity: 46.1554,
      poster_path: "/tsVYhgOvp2d3bv04yYScSQz6QoW.jpg",
      release_date: "2026-01-21",
      title: "重返寂静岭",
      video: false,
      vote_average: 5.5,
      vote_count: 15,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 225692,
            known_for_department: "Acting",
            name: "杰瑞米·艾文",
            original_name: "Jeremy Irvine",
            popularity: 2.1057,
            profile_path: "/gSEtyKl9InFkaDcAEd25eYrHSNB.jpg",
            cast_id: 3,
            character: "James Sunderland",
            credit_id: "6411e278a6c1040079067a17",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 1685904,
            known_for_department: "Acting",
            name: "汉娜·艾蜜莉·安德森",
            original_name: "Hannah Emily Anderson",
            popularity: 1.4221,
            profile_path: "/fSyNGF4pZQj9Ne9IKv9kfimECzk.jpg",
            cast_id: 4,
            character: "Mary Crane  / Angela / Maria / Moth Mary",
            credit_id: "6411e27fb4224200d8668aa0",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 3131371,
            known_for_department: "Acting",
            name: "Evie Templeton",
            original_name: "Evie Templeton",
            popularity: 4.9343,
            profile_path: "/1JV3FEULVnROl4APfkUprqTrFF6.jpg",
            cast_id: 41,
            character: "Laura",
            credit_id: "65d2856612425c017ce33ac6",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 2438347,
            known_for_department: "Acting",
            name: "Pearse Egan",
            original_name: "Pearse Egan",
            popularity: 0.4233,
            profile_path: "/bzHkytLIEk4T4arzd7h5BRLufov.jpg",
            cast_id: 50,
            character: "Eddie Dombrowski",
            credit_id: "66074994303c85017cb9dbde",
            order: 3,
          },
          {
            adult: false,
            gender: 1,
            id: 1092908,
            known_for_department: "Acting",
            name: "伊芙·麦克林",
            original_name: "Eve Macklin",
            popularity: 0.6573,
            profile_path: "/7e1bpd3iTst0PvCk4A7LVfUgNut.jpg",
            cast_id: 40,
            character: "Kaitlyn",
            credit_id: "65d2854e761421017cfeec0e",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 1675328,
            known_for_department: "Acting",
            name: "罗伯特斯荃奇",
            original_name: "Robert Strange",
            popularity: 1.234,
            profile_path: "/4GBjA1itRhsKaPaOrVE1YN9qOqc.jpg",
            cast_id: 49,
            character: "Red Pyramid / Pyramid Head",
            credit_id: "66074982e6271901490bd4e6",
            order: 5,
          },
          {
            adult: false,
            gender: 3,
            id: 2021091,
            known_for_department: "Acting",
            name: "Emily Carding",
            original_name: "Emily Carding",
            popularity: 0.3736,
            profile_path: "/zW0SKNWWlEFrLm5XAZh24rL0E6b.jpg",
            cast_id: 45,
            character: "Dara",
            credit_id: "65d285b12da8460185249b91",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 1770260,
            known_for_department: "Acting",
            name: "Martine Richards",
            original_name: "Martine Richards",
            popularity: 0.5804,
            profile_path: "/q7xxOnNsBZrxsMAOlkNQg5QPNj7.jpg",
            cast_id: 47,
            character: "Claudette",
            credit_id: "65d285d3a313b801646f80a3",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "近未来的地球黄沙遍野，小麦、秋葵等基础农作物相继因枯萎病灭绝，人类不再像从前那样仰望星空，放纵想象力和灵感的迸发，而是每日在沙尘暴的肆虐下倒数着所剩不多的光景。在家务农的前NASA宇航员库珀接连在女儿墨菲的书房发现奇怪的重力场现象，随即得知在某个未知区域内前NASA成员仍秘密进行一个拯救人类的计划。多年以前土星附近出现神秘虫洞，NASA借机将数名宇航员派遣到遥远的星系寻找适合居住的星球。在布兰德教授的劝说下，库珀忍痛告别了女儿，和其他三名专家教授女儿艾米莉亚·布兰德、罗米利、多伊尔搭乘宇宙飞船前往目前已知的最有希望的三颗星球考察。他们穿越遥远的星系银河，感受了一小时七年光阴的沧海桑田，窥见了未知星球和黑洞的壮伟与神秘。在浩瀚宇宙的绝望而孤独角落，总有一份超越了时空的笃定情怀将他们紧紧相连……",
      popularity: 42.9725,
      poster_path: "/c35Vwd9rmMQfaEJuUrJRF3LZWJX.jpg",
      release_date: "2014-11-05",
      title: "星际穿越",
      video: false,
      vote_average: 8.466,
      vote_count: 38682,
      credits: {
        cast: [
          {
            adult: false,
            gender: 2,
            id: 10297,
            known_for_department: "Acting",
            name: "马修·麦康纳",
            original_name: "Matthew McConaughey",
            popularity: 5.6405,
            profile_path: "/lCySuYjhXix3FzQdS4oceDDrXKI.jpg",
            cast_id: 9,
            character: "Cooper",
            credit_id: "52fe4bbf9251416c910e47cb",
            order: 0,
          },
          {
            adult: false,
            gender: 1,
            id: 1813,
            known_for_department: "Acting",
            name: "安妮·海瑟薇",
            original_name: "Anne Hathaway",
            popularity: 12.4428,
            profile_path: "/s6tflSD20MGz04ZR2R1lZvhmC4Y.jpg",
            cast_id: 169,
            character: "Brand",
            credit_id: "57fe146fc3a368504a00261e",
            order: 1,
          },
          {
            adult: false,
            gender: 2,
            id: 3895,
            known_for_department: "Acting",
            name: "迈克尔·凯恩",
            original_name: "Michael Caine",
            popularity: 3.8574,
            profile_path: "/bVZRMlpjTAO2pJK6v90buFgVbSW.jpg",
            cast_id: 18,
            character: "Professor Brand",
            credit_id: "52fe4bbf9251416c910e47f5",
            order: 2,
          },
          {
            adult: false,
            gender: 1,
            id: 83002,
            known_for_department: "Acting",
            name: "杰西卡·查斯坦",
            original_name: "Jessica Chastain",
            popularity: 5.6011,
            profile_path: "/bXFXSlfCzoE5Py7KBP9P0Y0Ot1v.jpg",
            cast_id: 17,
            character: "Murph",
            credit_id: "52fe4bbf9251416c910e47f1",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 1893,
            known_for_department: "Acting",
            name: "卡西·阿弗莱克",
            original_name: "Casey Affleck",
            popularity: 2.487,
            profile_path: "/304ilSygaCRWykoBWAL67TOw8g9.jpg",
            cast_id: 21,
            character: "Tom",
            credit_id: "52fe4bbf9251416c910e4805",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 8210,
            known_for_department: "Acting",
            name: "韦斯·本特利",
            original_name: "Wes Bentley",
            popularity: 2.006,
            profile_path: "/voD93lzFZrr9xfAggwFcPRBi84i.jpg",
            cast_id: 28,
            character: "Doyle",
            credit_id: "52fe4bbf9251416c910e4821",
            order: 5,
          },
          {
            adult: false,
            gender: 2,
            id: 17052,
            known_for_department: "Acting",
            name: "托弗·戈瑞斯",
            original_name: "Topher Grace",
            popularity: 2.7261,
            profile_path: "/oJQxl4DG0KSCtOGrpWNhYz9gUZA.jpg",
            cast_id: 27,
            character: "Getty",
            credit_id: "52fe4bbf9251416c910e481d",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 851784,
            known_for_department: "Acting",
            name: "麦肯基·弗依",
            original_name: "Mackenzie Foy",
            popularity: 2.7046,
            profile_path: "/wzH60SrqWp2XMkBfLgdBhx5EJ82.jpg",
            cast_id: 24,
            character: "Murph (10 Yrs.)",
            credit_id: "52fe4bbf9251416c910e4811",
            order: 7,
          },
        ],
      },
    },
    {
      adult: false,
      backdrop_path: "/uRDu9DiTVf97z5sj6qesmyQpYji.jpg",
      genre_ids: [18, 10749],
      id: 858024,
      original_language: "en",
      original_title: "Hamnet",
      overview:
        "讲述了一个关于爱与失落的感人至深的故事，正是这段经历启发了莎士比亚创作出其永恒的杰作《哈姆雷特》。",
      popularity: 45.7592,
      poster_path: "/wKGcgF3KS0luee7HjlzZF6hHKRH.jpg",
      release_date: "2025-11-26",
      title: "哈姆奈特",
      video: false,
      vote_average: 7.792,
      vote_count: 96,
      credits: {
        cast: [
          {
            adult: false,
            gender: 1,
            id: 1498158,
            known_for_department: "Acting",
            name: "杰茜·巴克利",
            original_name: "Jessie Buckley",
            popularity: 17.3619,
            profile_path: "/i8IlkFbZqKUgkypZKpdhrw00uqw.jpg",
            cast_id: 14,
            character: "Agnes",
            credit_id: "64501702eee18602e7888af7",
            order: 0,
          },
          {
            adult: false,
            gender: 2,
            id: 2326151,
            known_for_department: "Acting",
            name: "保罗·麦斯卡",
            original_name: "Paul Mescal",
            popularity: 3.2725,
            profile_path: "/vrzZ41TGNAFgfmZjC2sOJySzBLd.jpg",
            cast_id: 15,
            character: "Will",
            credit_id: "64501708bdd568111dcc51d3",
            order: 1,
          },
          {
            adult: false,
            gender: 1,
            id: 1639,
            known_for_department: "Acting",
            name: "艾米丽·沃森",
            original_name: "Emily Watson",
            popularity: 2.3763,
            profile_path: "/bd0qiJXHoLNpkCqABsh67AKRtjC.jpg",
            cast_id: 19,
            character: "Mary",
            credit_id: "66c4befeb56651991ed5a95f",
            order: 2,
          },
          {
            adult: false,
            gender: 2,
            id: 1496392,
            known_for_department: "Acting",
            name: "乔·阿尔文",
            original_name: "Joe Alwyn",
            popularity: 1.5697,
            profile_path: "/sRXx2tJkWrvS1THVG0h2OGlnTNm.jpg",
            cast_id: 18,
            character: "Bartholomew",
            credit_id: "66bf64519e47b5f38f97c329",
            order: 3,
          },
          {
            adult: false,
            gender: 2,
            id: 3115247,
            known_for_department: "Acting",
            name: "雅可比·朱佩",
            original_name: "Jacobi Jupe",
            popularity: 1.4679,
            profile_path: "/AbmnZOPvC1vA5yilvG3IyXdTSPB.jpg",
            cast_id: 25,
            character: "Hamnet",
            credit_id: "67350f354c0d01863c76eca1",
            order: 4,
          },
          {
            adult: false,
            gender: 2,
            id: 1590759,
            known_for_department: "Acting",
            name: "诺亚·尤佩",
            original_name: "Noah Jupe",
            popularity: 2.1553,
            profile_path: "/sOsr4SgcnVqpLofasvy0B6dxPuf.jpg",
            cast_id: 71,
            character: "Hamlet",
            credit_id: "68b31dd5fa934d43073ccb25",
            order: 5,
          },
          {
            adult: false,
            gender: 1,
            id: 4088089,
            known_for_department: "Acting",
            name: "Bodhi Rae Breathnach",
            original_name: "Bodhi Rae Breathnach",
            popularity: 1.2561,
            profile_path: "/sONxErk3r0xfoESAmU3GVTxoPDe.jpg",
            cast_id: 30,
            character: "Susanna",
            credit_id: "67350ff84955eacd19ea2349",
            order: 6,
          },
          {
            adult: false,
            gender: 1,
            id: 4945576,
            known_for_department: "Acting",
            name: "Olivia Lynes",
            original_name: "Olivia Lynes",
            popularity: 0.25,
            profile_path: "/rixOc0eAICCG5l2rtY42kcSoBjm.jpg",
            cast_id: 28,
            character: "Judith",
            credit_id: "67350fcf4c0d01863c76ecd6",
            order: 7,
          },
        ],
      },
    },
  ],
};

// API请求函数
async function fetchFromTMDB(endpoint) {
  const url = `${CONFIG.TMDB_BASE_URL}${endpoint}`;
  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${CONFIG.TMDB_TOKEN}`,
      accept: "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(`TMDB API Error: ${response.status}`);
  }

  return await response.json();
}

// 获取图片URL
function getImageUrl(path, size = "w500") {
  if (!path) return "";
  if (CONFIG.USE_MOCK) {
    // Mock模式使用TMDB图片链接
    return `${CONFIG.IMAGE_BASE_URL}/${size}${path}`;
  }
  return `${CONFIG.IMAGE_BASE_URL}/${size}${path}`;
}

// 获取即将上映电影列表
async function getUpcomingMovies() {
  if (CONFIG.USE_MOCK) {
    // 优先读取本地JSON
    try {
      const res = await fetch(`${CONFIG.LOCAL_DATA_BASE}/upcoming.json`, {
        cache: "no-cache",
      });
      if (res.ok) {
        const json = await res.json();
        return Array.isArray(json) ? json : json?.results || [];
      }
    } catch (e) {
      console.warn("读取本地 upcoming.json 失败，使用内置MOCK:", e);
    }
    return MOCK_DATA.upcoming;
  }

  try {
    const data = await fetchFromTMDB("/movie/upcoming?language=zh-CN&page=1");
    const results = data.results || [];
    // 同步写入本地JSON
    syncLocalData("upcoming", null, results);
    return results;
  } catch (error) {
    console.error("获取电影列表失败:", error);
    // 失败兜底：尝试读取本地JSON，否则使用内置MOCK
    try {
      const res = await fetch(`${CONFIG.LOCAL_DATA_BASE}/upcoming.json`, {
        cache: "no-cache",
      });
      if (res.ok) {
        const json = await res.json();
        return Array.isArray(json) ? json : json?.results || MOCK_DATA.upcoming;
      }
    } catch (_) {}
    return MOCK_DATA.upcoming;
  }
}

// 获取电影详情
async function getMovieDetail(movieId) {
  if (CONFIG.USE_MOCK) {
    // 优先读取本地详情JSON
    try {
      const res = await fetch(
        `${CONFIG.LOCAL_DATA_BASE}/movies/${movieId}.json`,
        { cache: "no-cache" },
      );
      if (res.ok) {
        return await res.json();
      }
    } catch (e) {
      console.warn(`读取本地 movies/${movieId}.json 失败，使用内置MOCK:`, e);
    }
    const movie = MOCK_DATA.upcoming.find((m) => m.id == movieId);

    return movie || null;
  }

  try {
    const movie = await fetchFromTMDB(`/movie/${movieId}?language=zh-CN`);
    const credits = await fetchFromTMDB(
      `/movie/${movieId}/credits?language=zh-CN`,
    );
    const combined = {
      ...movie,
      credits: {
        cast: (credits?.cast || []).slice(0, 8),
      },
    };
    // 同步写入本地详情JSON
    syncLocalData("movie", movieId, combined);
    return combined;
  } catch (error) {
    console.error("获取电影详情失败:", error);
    // 失败兜底：尝试读取本地JSON，否则使用内置MOCK
    try {
      const res = await fetch(
        `${CONFIG.LOCAL_DATA_BASE}/movies/${movieId}.json`,
        { cache: "no-cache" },
      );
      if (res.ok) {
        return await res.json();
      }
    } catch (_) {}
    const movie = MOCK_DATA.upcoming.find((m) => m.id == movieId);
    return movie || null;
  }
}

// 同步写入本地JSON（通过本地服务提供的写接口）
function syncLocalData(type, id, payload) {
  const url =
    type === "upcoming"
      ? `${CONFIG.LOCAL_SYNC_BASE}/upcoming`
      : `${CONFIG.LOCAL_SYNC_BASE}/movie/${id}`;
  fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  }).catch((e) => {
    console.warn("同步本地JSON请求失败（可忽略，服务未启动或权限不足）:", e);
  });
}

// 生成星星评分
function generateStars(rating) {
  const fullStars = Math.floor(rating / 2);
  const hasHalfStar = rating % 2 >= 1;
  const emptyStars = 5 - fullStars - (hasHalfStar ? 1 : 0);

  let stars = "★".repeat(fullStars);
  if (hasHalfStar) stars += "☆";
  stars += "☆".repeat(emptyStars);

  return stars;
}
